stages:
  - build

variables:
  DOCKER_IMAGE: $CI_REGISTRY/$CI_REGISTRY_USER/$CI_PROJECT_NAME

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  
  before_script:
    - apk add --no-cache docker-cli
    - export TAG=${CI_COMMIT_SHORT_SHA}
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  script:
    - echo "Build image Docker"
    - docker build -t $DOCKER_IMAGE:$TAG .

    - echo "Pushing Docker image to Docker Hub"
    - docker push $DOCKER_IMAGE:$TAG
    
  only:
    - main
